[package]
name = "daibo_kv"
version = "0.1.0"
authors = ["daibo83 <linh@goong.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fst = "0.4.7"
memmap = "0.7.0"
